@startuml
actor       User        as user
control     Logic       as logic
participant Service     as service
entity      Bid         as bid

user -> logic : 任务
logic -> service : To boundary
service -> bid : To control
@enduml